# Generated by Django 5.2.8 on 2025-11-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_code', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='name',
            field=models.CharField(
                default='Untitled QR Code', help_text='Name of the QR code', max_length=255
            ),
        ),
    ]
