# Generated by Django 6.0 on 2025-12-13 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_code', '0006_add_qr_type_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrcode',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'QR Code',
                'verbose_name_plural': 'QR Codes',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='credits',
            field=models.PositiveBigIntegerField(
                default=0, help_text='Current credits balance (1 credit = $0.01).'
            ),
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'amount',
                    models.IntegerField(
                        help_text='Credits added (positive) or spent (negative). 1 credit = $0.01.'
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('purchase', 'Purchase'),
                            ('spend', 'Spend'),
                            ('adjustment', 'Adjustment'),
                            ('refund', 'Refund'),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    'description',
                    models.CharField(
                        blank=True,
                        default='',
                        help_text='Human-readable notes describing why this transaction happened.',
                        max_length=255,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='credit_transactions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [
                    models.Index(
                        fields=['user', '-created_at'], name='qr_code_cre_user_id_3577de_idx'
                    )
                ],
            },
        ),
    ]
