"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: PROJECT_ROOT / 'subdir'.
# PROJECT_ROOT, aka BASE_DIR.
PROJECT_ROOT = Path(__file__).resolve().parents[1]

# Load environment variables from the selected `.env.<ENVIRONMENT>` file.
# This must happen before reading any `os.getenv(...)` values.
try:
    import sys

    # Test runs and static analysis may have multiple env files in the repo; default to dev.
    if 'pytest' in sys.modules or 'mypy' in sys.modules:
        os.environ.setdefault('ENVIRONMENT', 'dev')

    from src.qr_code.common.environment import select_env

    _selection = select_env(PROJECT_ROOT)
    if _selection.errors:
        raise RuntimeError('\n'.join(_selection.errors))
    if _selection.environment:
        os.environ.setdefault('ENVIRONMENT', _selection.environment)
        load_dotenv(dotenv_path=_selection.env_path)
    else:
        raise RuntimeError('Environment not set.')
except Exception:
    # Fail fast if env selection is broken; otherwise we'd silently read wrong defaults.
    raise


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'SECRET_KEY', 'django-insecure-8eho-(3@jki^spuj0q%+k!m9a@%d82mqy+fxe65w)6jr_e=ld2'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ['true', '1']

ALLOWED_HOSTS: list[str] = ['localhost', '127.0.0.1', 'joaonc.pythonanywhere.com']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'src.qr_code',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [PROJECT_ROOT / 'src' / 'qr_code' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': PROJECT_ROOT / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 6,
        },
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    PROJECT_ROOT / 'src' / 'qr_code' / 'static',
]
STATIC_ROOT = PROJECT_ROOT / 'staticfiles'

# WhiteNoise configuration for serving static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = PROJECT_ROOT / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'qr_code.User'

# Login URL for @login_required decorator
LOGIN_URL = '/login/'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ('rest_framework.authentication.SessionAuthentication',),
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticated',),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Migrations: store app migrations at project root under migrations/
MIGRATION_MODULES = {
    'qr_code': 'migrations',
}

# QR Code settings
BASE_URL = os.getenv('BASE_URL', 'http://localhost:8010')
QR_CODE_REDIRECT_PATH = '/go/'

# Password reset settings
PASSWORD_RESET_TOKEN_TTL_HOURS = int(os.getenv('PASSWORD_RESET_TOKEN_TTL_HOURS', '4'))

# Email confirmation settings
EMAIL_CONFIRMATION_TOKEN_TTL_HOURS = int(os.getenv('EMAIL_CONFIRMATION_TOKEN_TTL_HOURS', '48'))

# Email settings
# Comma-separated list of email backends to use. Example: "console" or "ses,console".
EMAIL_BACKENDS = os.getenv('EMAIL_BACKENDS', '')

# Tests should not require external configuration.
if not EMAIL_BACKENDS:
    import sys

    if 'pytest' in sys.modules:
        EMAIL_BACKENDS = 'console'

AWS_SES_SENDER = os.getenv('AWS_SES_SENDER', 'no-reply@example.com')

# Jazzmin configuration
JAZZMIN_SETTINGS = {
    'site_title': 'QR Code Admin',
    'site_header': 'QR Code Administration',
    'site_brand': 'QR Code',
    'welcome_sign': 'QR Code Admin',
    'copyright': 'QR Code Project',
    'search_model': ['qr_code.User', 'qr_code.QRCode'],
    'user_avatar': None,
    'login_logo': 'images/logo_128x128.png',
    'site_logo': 'images/logo_128x128.png',
    'show_sidebar': True,
    'navigation_expanded': True,
    'theme': 'default',
    'dark_mode_theme': 'darkly',
    'icons': {
        'auth': 'fas fa-users-cog',
        'auth.user': 'fas fa-user',
        'auth.Group': 'fas fa-users',
        'qr_code.QRCode': 'fas fa-qrcode',
        'qr_code.User': 'fas fa-user-circle',
        'qr_code.TimeLimitedToken': 'fas fa-key',
    },
    'default_icon_parents': 'fas fa-chevron-right',
    'default_icon_children': 'fas fa-arrow-right',
    'related_modal_active': True,
    'custom_links': {
        'qr_code': [
            {
                'name': 'Admin Tools',
                'url': '/admin/tools/',
                'permissions': ['auth.add_user'],
                'icon': 'fas fa-tools',
            }
        ],
    },
    'custom_css': 'css/jazzmin_custom.css',
    'custom_js': 'js/admin_theme_toggle.js',
}
