# Generated by Django 5.2 on 2025-10-16 18:02

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'content',
                    models.TextField(help_text='The actual content encoded in the QR code'),
                ),
                (
                    'original_url',
                    models.URLField(
                        blank=True,
                        help_text='Original URL if content is a shortened URL',
                        max_length=2000,
                        null=True,
                    ),
                ),
                (
                    'use_url_shortening',
                    models.BooleanField(default=False, help_text='Whether to use URL shortening'),
                ),
                (
                    'short_code',
                    models.CharField(
                        blank=True,
                        help_text='Short code for URL shortening',
                        max_length=16,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    'qr_format',
                    models.CharField(
                        choices=[('png', 'PNG'), ('svg', 'SVG'), ('jpeg', 'JPEG')],
                        default='png',
                        max_length=10,
                    ),
                ),
                (
                    'size',
                    models.IntegerField(default=10, help_text='Scale factor for QR code size'),
                ),
                (
                    'error_correction',
                    models.CharField(
                        choices=[
                            ('L', 'Low (~7%)'),
                            ('M', 'Medium (~15%)'),
                            ('Q', 'Quartile (~25%)'),
                            ('H', 'High (~30%)'),
                        ],
                        default='M',
                        max_length=1,
                    ),
                ),
                ('border', models.IntegerField(default=4, help_text='Border size (quiet zone)')),
                (
                    'background_color',
                    models.CharField(
                        default='white',
                        help_text="Background color (hex, name, or 'transparent')",
                        max_length=20,
                    ),
                ),
                (
                    'foreground_color',
                    models.CharField(
                        default='black', help_text='Foreground (data) color', max_length=20
                    ),
                ),
                (
                    'image_file',
                    models.CharField(help_text='Path to generated image file', max_length=255),
                ),
                (
                    'scan_count',
                    models.IntegerField(default=0, help_text='Number of times QR code was scanned'),
                ),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                (
                    'created_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='qrcodes',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['short_code'], name='qrcodes_qrc_short_c_49fa76_idx'),
                    models.Index(
                        fields=['created_by', '-created_at'], name='qrcodes_qrc_created_7e2fb5_idx'
                    ),
                ],
            },
        ),
    ]
