# Generated by Django 6.0 on 2025-12-06 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_code', '0002_passwordresettoken'),
    ]

    operations = [
        # Add email confirmation fields to User
        migrations.AddField(
            model_name='user',
            name='email_confirmed',
            field=models.BooleanField(default=False, help_text='Whether email is confirmed'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When email was confirmed', null=True),
        ),
        # Rename PasswordResetToken to TimeLimitedToken
        migrations.RenameModel(
            old_name='PasswordResetToken',
            new_name='TimeLimitedToken',
        ),
        # Update metadata
        migrations.AlterModelOptions(
            name='timelimitedtoken',
            options={
                'verbose_name': 'Time-limited token',
                'verbose_name_plural': 'Time-limited tokens',
            },
        ),
        # Rename the related_name
        migrations.AlterField(
            model_name='timelimitedtoken',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='time_limited_tokens',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # Add token_type field with default for existing records
        migrations.AddField(
            model_name='timelimitedtoken',
            name='token_type',
            field=models.CharField(
                choices=[
                    ('password_reset', 'Password Reset'),
                    ('email_confirmation', 'Email Confirmation'),
                ],
                max_length=32,
                default='password_reset',  # Existing tokens are password reset tokens
            ),
            preserve_default=False,
        ),
        # Add index
        migrations.AddIndex(
            model_name='timelimitedtoken',
            index=models.Index(fields=['token', 'token_type'], name='qr_code_tim_token_af54ac_idx'),
        ),
    ]
