# Generated by Django 6.0 on 2025-12-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_code', '0003_user_email_confirmed_user_email_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='deleted_at',
            field=models.DateTimeField(
                blank=True, help_text='Timestamp when QR code was soft-deleted', null=True
            ),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['deleted_at'], name='qr_code_qrc_deleted_109f43_idx'),
        ),
    ]
